global:
  scrape_interval: 5s

scrape_configs:
  - job_name: model-server
    metrics_path: /metrics
    static_configs:
      - targets: [model-server:8000]

  - job_name: dcgm-exporter
    scrape_interval: 1s
    static_configs:
      - targets: [dcgm-exporter:9400]
