services:
  httpbin:
    image: kong/httpbin:0.2.1
    container_name: httpbin
    ports:
      - "8000:80"
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:v1.31.4
    container_name: envoy
    volumes:
      - ./config.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
    entrypoint: ["envoy"]
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped
