repositories:
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server

environments:
  default:
    values:
    - global:
        clusterName: karpenter-demo
    - karpenter:
        interruptionQueue: karpenter-demo
        irsa: arn:aws:iam::467606240901:role/karpenter-demo-karpenter-irsa

releases:
- name: karpenter
  namespace: karpenter
  chart: oci://public.ecr.aws/karpenter/karpenter
  version: 1.1.1
  values:
  - ./charts/karpenter.gotmpl
- name: metrics-server
  namespace: kube-system
  chart: metrics-server/metrics-server
  version: 3.12.2
  values:
  - ./charts/metrics-server.yaml
