# Knative Serving Webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activator
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: activator
        resources:
          requests:
            cpu: 300m
            memory: 60Mi
          limits:
            cpu: 300m
            memory: 60Mi
---
# Knative Serving Webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: autoscaler
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
# Knative Serving Webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: controller
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
# Knative Serving Webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-istio-controller
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: controller
        resources:
          requests:
            cpu: 30m
            memory: 40Mi
          limits:
            cpu: 30m
            memory: 40Mi
---
# Knative Serving Webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-istio-webhook
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: webhook
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 20m
            memory: 20Mi
---
# Knative Serving Webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: webhook
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
