apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-use-cp
spec:
  selector:
    matchLabels:
      app: not-use-cp
  replicas: 1
  template:
    metadata:
      labels:
        app: not-use-cp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - no-use-dabase-connection
      containers:
      - name: not-use-cp
        image: docker.io/choisunguk/hikaricp:jdbc-v1
        env:
        - name: JAVA_OPTS
          value: "-Dspring.profiles.active=docker"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 1Gi
            cpu: "500m"
          limits:
            memory: 1Gi
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: not-use-cp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: not-use-cp
