server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: elasticache-client-noauth
  data:
    redis:
      host: ${ELASTICACHE_ENDPOINT}
      port: ${ELASTICACHE_PORT:6379}
      connect-timeout: 3s
      timeout: 3s
      ssl:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
