{
 "title": "k6 influxdb 2.X",
 "description": "k6 for influxdb 2.x version(Flux)\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Data_received-수신된 데이터의 양",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"data_received\")\r\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"derivative\")"
    },
    {}
   ]
  },
  {
   "title": "Data_sent(전송한 데이터 량)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"data_sent\")\r\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "vus(Virtual Users)_max-가상 유저의 최대 가능한 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vus_max\")\r\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "vus(Virtual Users)-현재 총 활동하는 가상유저",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vus\")\r\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"derivative\")\r\n  "
    }
   ]
  },
  {
   "title": "http_req_receiving-원격 호스트로 부터 데이터를 수신하는데 걸린 시간",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_receiving\")\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "http_req_waiting-원격 호스트로 부터 응답을 기다리는 시간 (첫번째 바이트가 온 시간 혹은 TTFB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 15 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_waiting\")\r\n  |> yield(name: \"derivative\")\r\n  "
    }
   ]
  },
  {
   "title": "http_req_sending-원격 호스트에 데이터를 전송하는데 걸린 시간",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_sending\")\r\n  |> yield(name: \"derivative\")\r\n  "
    }
   ]
  },
  {
   "title": "http_req_duration(http_req_sending + http_req_waiting + http_req_receiving)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> yield(name: \"derivative\")\r\n"
    }
   ]
  },
  {
   "title": "Http_req_blocked-TCP 커넥션 슬롯에 대해서 대기한시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_blocked\")\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "http_req_duration+http_req_blocked",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" or r._measurement == \"http_req_blocked\")\r\n  |> yield(name: \"derivative\")\r\n"
    }
   ]
  },
  {
   "title": "http_req_failed-setResponseCallback에 따른 요청 실패율",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_failed\")\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "http_reqs-총 요청수(k6)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "http_req_tls_handshaking-원격 호스트와 TLS 세션 핸드쉐이킹에 소요된 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_tls_handshaking\")\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "http_req_connecting-원격 호스트와 TCP 커넥션을 만들기 까지 소요된 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_connecting\")\r\n  |> yield(name: \"derivative\")"
    }
   ]
  }
 ]
}