apiVersion: v1
kind: Service
metadata:
  name: service-a-pr-101
  namespace: pr-preview
  labels:
    app.kubernetes.io/name: service-a
    app.kubernetes.io/instance: pr-101
    app.kubernetes.io/part-of: pr-preview-kind
spec:
  selector:
    app.kubernetes.io/name: service-a
    app.kubernetes.io/instance: pr-101
  ports:
    - name: http
      port: 8080
      targetPort: 8080
