services:
  fastapi_app:
    image: test:v1-rc.2
    container_name: fastapi_app_container
    ports:
      - "8000:8000"
    environment:
      # DB 접속 정보 (MySQL 서비스 이름을 호스트로 사용)
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password1234
      DB_NAME: testdb
      PYTHONUNBUFFERED: 1
    networks:
      - test_net
    depends_on:
      mysql_db: # MySQL 서비스가 healthcheck 통과 후 시작하도록
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mysql_db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: testdb
      # MYSQL_USER: app_user
      # MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    networks:
      - test_net
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      # .env 파일에서 초기 설정값 참조
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password1234
      DOCKER_INFLUXDB_INIT_ORG: my_org
      DOCKER_INFLUXDB_INIT_BUCKET: k6_results
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: password1234
    networks:
      - test_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password1234
    # import influxDB dashboard
    volumes:
      - ../../../tools/k6/docker-config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - test_net
    depends_on:
      - influxdb

networks:
  test_net:
    driver: bridge

volumes:
  mysql_data:
  influxdb_data:
