kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocd
nodes:
- role: control-plane
  image: kindest/node:v1.30.4
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
