IMAGE_NAME = "centos/7"
IP = "192.168.25.45"
HOSTNAME = "aws-dcos"
CPU = 4
RAM = 4096

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # master node
  config.vm.define HOSTNAME do |cfg|
    cfg.vm.box = IMAGE_NAME
    cfg.vm.network "public_network", ip: IP
    cfg.vm.hostname = HOSTNAME
    
    cfg.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
      v.name = HOSTNAME
    end

    cfg.vm.provision "shell", inline: <<-SCRIPT
      yum install epel-release -y
      yum install vim git tree wget net-tools -y
      sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
    SCRIPT

    # install docker
    cfg.vm.provision "shell", inline: <<-SCRIPT
      yum install -y yum-utils unzip
      wget https://releases.hashicorp.com/terraform/0.11.0/terraform_0.11.0_linux_amd64.zip
      unzip terraform_0.11.0_linux_amd64.zip -d /usr/local/bin/
    SCRIPT
  end
end