pullRequest:
  number: ""

workload:
  name: app-workload
  image: choisunguk/pull-request-generator:v1
  imagePullPolicy: IfNotPresent
  port: 8080
  destinationUrl: http://app-service.prod.svc.cluster.local:8080/work
  extraEnv: []
  resources:
    requests:
      cpu: 250m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 192Mi

service:
  name: app-service
  port: 8080

waypoint:
  name: waypoint
  namespace: istio-waypoint

httpRoute:
  enabled: false
  name: ""
  namespace: ""
  parentRef:
    group: ""
    kind: Service
    name: app-service
    namespace: prod
    port: null
  hostname: ""
  pathPrefix: /
  header:
    enabled: false
    type: RegularExpression
    name: cookie
    value: ""
  backend:
    group: ""
    kind: Service
    name: ""
    namespace: ""
    port: null
  fallback:
    enabled: true
    group: ""
    kind: Service
    name: ""
    namespace: ""
    port: null

referenceGrant:
  enabled: true
  name: allow-route
