---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-920
spec:
  selector:
    matchLabels:
      app: backend-920
  template:
    metadata:
      labels:
        app: backend-920
    spec:
      containers:
      - name: backend-920
        image: choisunguk/fcm-push:9.2.0-rc.2
        resources:
          limits:
            memory: "2Gi"
            cpu: "4"
          requests:
            memory: "2Gi"
            cpu: "4"
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >
            -XX:InitialRAMPercentage=65.0 -XX:MaxRAMPercentage=65.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: firebase-volume
          mountPath: /app/firebase-adminsdk.json
          subPath: firebase-adminsdk.json
      volumes:
      - name: firebase-volume
        secret:
          secretName: firebase-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-920
  labels:
    app: backend-920
spec:
  type: NodePort
  selector:
    app: backend-920
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot920
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: backend-920
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
