apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: netshoot
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: [ "/bin/sleep", "infinity" ]
