apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  # ref: https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-distribution
  trafficDistribution: PreferClose
