apiVersion: v1
kind: Pod
metadata:
  name: broken-nginx
  labels:
    app: broken-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.99-totally-fake-tag
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
