apiVersion: v1
kind: Service
metadata:
  name: httpbin-v2
  namespace: httpbin
  labels:
    app: httpbin-v2
    app.kubernetes.io/name: kgateway-quickstart
    app.kubernetes.io/component: routing
spec:
  selector:
    app: httpbin-v2
  ports:
    - name: http
      port: 8000
      targetPort: 8080
