apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- github.com/argoproj/argo-cd/manifests/base?ref=stable
- github.com/argoproj/argo-cd/manifests/crds?ref=stable
- github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=stable
- ./patches/argocd-project-bootstrap.yaml
# - ./patches/argocd-ingress.yaml

# patches:
# Argo Rollouts Extension 설치
# https://github.com/argoproj-labs/argocd-extension-metrics#install-ui-extension
# - path: patches/argocd-server-deployment.yaml
#   target:
#     kind: Deployment
#     name: argocd-server
# - path: patches/argocd-rbac-cm.yaml
#   target:
#     name: argocd-rbac-cm
# - path: patches/argocd-cm.yaml
#   target:
#     kind: ConfigMap
#     name: argocd-cm
