kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: security
nodes:
- role: control-plane
  image: kindest/node:v1.29.1
  extraPortMappings:
  # webgoat
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP
  # webgoat
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
- role: worker
  image: kindest/node:v1.29.1
- role: worker
  image: kindest/node:v1.29.1
