kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: security
nodes:
- role: control-plane
  image: kindest/node:v1.29.1
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # nginx ingress controller
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # nginx ingress controller
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.29.1
- role: worker
  image: kindest/node:v1.29.1
