environments:
  default:
    values:
    - global:
        clusterName: userdata
    - karpenter:
        interruptionQueue: userdata
        irsa: arn:aws:iam::467606240901:role/userdata-karpenter-irsa

releases:
- name: karpenter
  namespace: karpenter
  chart: oci://public.ecr.aws/karpenter/karpenter
  version: 1.1.1
  values:
  - ./charts/karpenter.gotmpl
