apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dvwa
subjects:
- kind: ServiceAccount
  name: dvwa
  namespace: dvwa
roleRef:
  kind: ClusterRole
  name: dvwa
  apiGroup: rbac.authorization.k8s.io
# ---
# 권한 축소
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: dvwa
#   namespace: dvwa
# subjects:
# - kind: ServiceAccount
#   name: dvwa
#   namespace: dvwa
# roleRef:
#   kind: Role
#   name: dvwa
#   apiGroup: rbac.authorization.k8s.io
