apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dvwa
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
# ---
# # 권한축소
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: dvwa
#   namespace: dvwa
# rules: []
