apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-assets-pvc
  labels:
    app.kubernetes.io/name: model-assets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
