apiVersion: v1
kind: Service
metadata:
  name: fastapi-auth-demo
  namespace: default
spec:
  selector:
    app: fastapi-auth-demo
  type: ClusterIP
  ports:
  - name: fastapi-auth-demo
    protocol: TCP
    port: 80
    targetPort: 80