server:
  port: 8082

spring:
  application:
    name: HikariCPApp

  datasource:
    url: jdbc:mysql://mysql:3306/sakila
    username: root
    password: NwmaZk$2f2pq27p^^4am
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP-Pool
