[project]
name = "mcp-and-openwebui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hf-transfer>=0.1.9",
    "openai>=1.98.0",
    "strands-agents>=1.1.0",
    "strands-agents-tools>=0.2.2",
]
