apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tcp-echo-envoy.fullname" . }}-config
  labels:
    {{- include "tcp-echo-envoy.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    {{- .Values.config | nindent 4 }}
