apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: kubeflow-user-example-com
  annotations:
    serving.kserve.io/s3-endpoint: minio-service.kubeflow.svc.cluster.local:9000
    serving.kserve.io/s3-usehttps: "0" # MinIO가 HTTP를 사용
    # serving.kserve.io/s3-region: us-east-1
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serving
  namespace: kubeflow-user-example-com
secrets:
- name: minio-secret
