apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  labels:
    app: dns-test
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: tools
    image: nicolaka/netshoot:v0.13
    command: [ "sleep", "infinity" ]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
