apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: vllm-local
  labels:
    app.kubernetes.io/name: vllm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
