# Tensorboard Controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard-controller-deployment
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 128Mi
