apiVersion: v1
kind: PersistentVolume
metadata:
  name: chapter5-s3files-pv
  labels:
    app.kubernetes.io/name: chapter5-s3files
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3files-static
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "s3files:${S3FILES_FILE_SYSTEM_ID}::${S3FILES_ACCESS_POINT_ID}"
