apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chapter5-s3files-pvc
  namespace: jupyterhub
  labels:
    app.kubernetes.io/name: chapter5-s3files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3files-static
  volumeName: chapter5-s3files-pv
  resources:
    requests:
      storage: 20Gi
