apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: example
spec:
  amiFamily: AL2023

  amiSelectorTerms:
  - name: amazon-eks-node-al2023-x86_64-standard-1.30-v20241115

  role: "userdata-eks-worker-node-role" # change to your worker node IAM role

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "userdata" # change to your VPC subnet tags

  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: "userdata" # change to your Security Group tags
      kubernetes.io/cluster/userdata: "owned"

  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 20Gi
      volumeType: gp3
      encrypted: true

  userData: |
    #!/bin/bash
    dnf update -y
    dnf install -y nginx
    systemctl start nginx
    systemctl enable nginx
