export interface ToneCurvePoints {
  blacks: number
  shadows: number
  midtones: number
  highlights: number
  whites: number
}

export interface FilmPreset {
  id: string
  name: string
  category: "color-negative" | "color-positive" | "bw" | "cinema"
  colorMatrix: number[]
  toneCurve: { r: ToneCurvePoints; g: ToneCurvePoints; b: ToneCurvePoints }
  saturation: number
  temperature: number
  tint: number
  grain: { amount: number; size: number }
  vignette: number
  fadeAmount: number
  description: string
}

const IDENTITY_MATRIX = [1, 0, 0, 0, 1, 0, 0, 0, 1]
const NEUTRAL_CURVE: ToneCurvePoints = { blacks: 0, shadows: 0, midtones: 0, highlights: 0, whites: 255 }

export const FILM_PRESETS: FilmPreset[] = [
  {
    id: "original",
    name: "Original",
    category: "color-negative",
    colorMatrix: IDENTITY_MATRIX,
    toneCurve: { r: { ...NEUTRAL_CURVE }, g: { ...NEUTRAL_CURVE }, b: { ...NEUTRAL_CURVE } },
    saturation: 1.0,
    temperature: 0,
    tint: 0,
    grain: { amount: 0, size: 1 },
    vignette: 0,
    fadeAmount: 0,
    description: "No film effect applied",
  },
  {
    id: "portra-160",
    name: "Portra 160",
    category: "color-negative",
    colorMatrix: [1.05, 0.02, -0.02, -0.01, 1.02, 0.01, -0.02, 0.05, 0.95],
    toneCurve: {
      r: { blacks: 8, shadows: 3, midtones: 2, highlights: -2, whites: 250 },
      g: { blacks: 6, shadows: 2, midtones: 0, highlights: -1, whites: 248 },
      b: { blacks: 12, shadows: 5, midtones: -3, highlights: -4, whites: 242 },
    },
    saturation: 0.88,
    temperature: 4,
    tint: -2,
    grain: { amount: 12, size: 2 },
    vignette: 0.15,
    fadeAmount: 8,
    description: "Soft, natural skin tones with gentle pastel rendering",
  },
  {
    id: "portra-400",
    name: "Portra 400",
    category: "color-negative",
    colorMatrix: [1.08, 0.03, -0.03, -0.02, 1.04, 0.02, -0.03, 0.06, 0.92],
    toneCurve: {
      r: { blacks: 10, shadows: 5, midtones: 3, highlights: -1, whites: 248 },
      g: { blacks: 8, shadows: 3, midtones: 1, highlights: -2, whites: 246 },
      b: { blacks: 14, shadows: 6, midtones: -4, highlights: -5, whites: 238 },
    },
    saturation: 0.92,
    temperature: 6,
    tint: -1,
    grain: { amount: 18, size: 2 },
    vignette: 0.18,
    fadeAmount: 10,
    description: "Warm tones with slightly more grain, versatile portrait film",
  },
  {
    id: "portra-800",
    name: "Portra 800",
    category: "color-negative",
    colorMatrix: [1.1, 0.04, -0.04, -0.02, 1.05, 0.03, -0.04, 0.08, 0.88],
    toneCurve: {
      r: { blacks: 14, shadows: 8, midtones: 5, highlights: 0, whites: 245 },
      g: { blacks: 10, shadows: 5, midtones: 2, highlights: -2, whites: 244 },
      b: { blacks: 18, shadows: 10, midtones: -5, highlights: -6, whites: 234 },
    },
    saturation: 0.85,
    temperature: 8,
    tint: 0,
    grain: { amount: 28, size: 3 },
    vignette: 0.22,
    fadeAmount: 14,
    description: "Higher grain with warm golden tones, great for low light",
  },
  {
    id: "ektar-100",
    name: "Ektar 100",
    category: "color-negative",
    colorMatrix: [1.15, -0.05, 0.02, -0.02, 1.1, -0.02, 0.03, -0.08, 1.12],
    toneCurve: {
      r: { blacks: 4, shadows: -2, midtones: 5, highlights: 3, whites: 252 },
      g: { blacks: 3, shadows: -1, midtones: 3, highlights: 2, whites: 250 },
      b: { blacks: 5, shadows: 2, midtones: 6, highlights: 4, whites: 248 },
    },
    saturation: 1.25,
    temperature: -2,
    tint: 0,
    grain: { amount: 8, size: 1 },
    vignette: 0.12,
    fadeAmount: 4,
    description: "Ultra-vivid colors with fine grain, punchy landscape film",
  },
  {
    id: "gold-200",
    name: "Gold 200",
    category: "color-negative",
    colorMatrix: [1.12, 0.05, -0.03, 0.02, 1.06, -0.02, -0.05, 0.02, 0.88],
    toneCurve: {
      r: { blacks: 12, shadows: 6, midtones: 4, highlights: 0, whites: 250 },
      g: { blacks: 8, shadows: 4, midtones: 2, highlights: -1, whites: 248 },
      b: { blacks: 6, shadows: 0, midtones: -6, highlights: -8, whites: 238 },
    },
    saturation: 1.05,
    temperature: 12,
    tint: 2,
    grain: { amount: 20, size: 2 },
    vignette: 0.2,
    fadeAmount: 12,
    description: "Warm, golden consumer film with nostalgic character",
  },
  {
    id: "ultramax-400",
    name: "Ultramax 400",
    category: "color-negative",
    colorMatrix: [1.1, 0.04, -0.02, 0.01, 1.05, -0.01, -0.03, 0.04, 0.9],
    toneCurve: {
      r: { blacks: 10, shadows: 4, midtones: 3, highlights: 1, whites: 250 },
      g: { blacks: 8, shadows: 3, midtones: 1, highlights: -1, whites: 248 },
      b: { blacks: 8, shadows: 2, midtones: -4, highlights: -5, whites: 240 },
    },
    saturation: 1.1,
    temperature: 8,
    tint: 1,
    grain: { amount: 22, size: 2 },
    vignette: 0.18,
    fadeAmount: 10,
    description: "Punchy everyday film with strong warm cast",
  },
  {
    id: "velvia-50",
    name: "Velvia 50",
    category: "color-positive",
    colorMatrix: [1.2, -0.08, 0.04, -0.04, 1.15, -0.04, 0.02, -0.1, 1.18],
    toneCurve: {
      r: { blacks: 2, shadows: -4, midtones: 6, highlights: 5, whites: 254 },
      g: { blacks: 2, shadows: -3, midtones: 8, highlights: 6, whites: 253 },
      b: { blacks: 3, shadows: -2, midtones: 5, highlights: 4, whites: 252 },
    },
    saturation: 1.4,
    temperature: -3,
    tint: 1,
    grain: { amount: 6, size: 1 },
    vignette: 0.1,
    fadeAmount: 2,
    description: "Extremely vivid slide film, legendary for landscapes",
  },
  {
    id: "provia-100f",
    name: "Provia 100F",
    category: "color-positive",
    colorMatrix: [1.08, -0.03, 0.02, -0.02, 1.06, -0.01, 0.01, -0.04, 1.06],
    toneCurve: {
      r: { blacks: 3, shadows: -1, midtones: 2, highlights: 1, whites: 252 },
      g: { blacks: 3, shadows: -1, midtones: 2, highlights: 1, whites: 252 },
      b: { blacks: 4, shadows: 0, midtones: 2, highlights: 1, whites: 251 },
    },
    saturation: 1.12,
    temperature: 0,
    tint: 0,
    grain: { amount: 8, size: 1 },
    vignette: 0.08,
    fadeAmount: 3,
    description: "Neutral, balanced slide film for all-around use",
  },
  {
    id: "superia-400",
    name: "Superia 400",
    category: "color-negative",
    colorMatrix: [1.06, 0.03, -0.02, 0.01, 1.04, 0.01, -0.02, 0.08, 0.92],
    toneCurve: {
      r: { blacks: 10, shadows: 4, midtones: 2, highlights: -1, whites: 248 },
      g: { blacks: 12, shadows: 5, midtones: 4, highlights: 0, whites: 250 },
      b: { blacks: 8, shadows: 2, midtones: -2, highlights: -4, whites: 240 },
    },
    saturation: 1.02,
    temperature: 5,
    tint: 3,
    grain: { amount: 22, size: 2 },
    vignette: 0.2,
    fadeAmount: 10,
    description: "Green-shifted consumer film with warm undertones",
  },
  {
    id: "pro-400h",
    name: "Pro 400H",
    category: "color-negative",
    colorMatrix: [0.98, 0.04, 0.02, 0.01, 1.02, 0.04, 0.02, 0.06, 0.96],
    toneCurve: {
      r: { blacks: 10, shadows: 4, midtones: -2, highlights: -3, whites: 246 },
      g: { blacks: 8, shadows: 3, midtones: 0, highlights: -1, whites: 248 },
      b: { blacks: 12, shadows: 6, midtones: 2, highlights: 0, whites: 248 },
    },
    saturation: 0.82,
    temperature: -2,
    tint: -3,
    grain: { amount: 16, size: 2 },
    vignette: 0.15,
    fadeAmount: 10,
    description: "Soft pastel tones with cool highlights, discontinued legend",
  },
  {
    id: "c200",
    name: "C200",
    category: "color-negative",
    colorMatrix: [1.08, 0.02, -0.01, 0.01, 1.04, 0.0, -0.02, 0.03, 0.92],
    toneCurve: {
      r: { blacks: 8, shadows: 3, midtones: 2, highlights: 0, whites: 250 },
      g: { blacks: 10, shadows: 4, midtones: 3, highlights: 1, whites: 250 },
      b: { blacks: 6, shadows: 1, midtones: -3, highlights: -4, whites: 242 },
    },
    saturation: 1.05,
    temperature: 4,
    tint: 2,
    grain: { amount: 18, size: 2 },
    vignette: 0.18,
    fadeAmount: 8,
    description: "Budget-friendly film with pleasant warm greens",
  },
  {
    id: "tri-x-400",
    name: "Tri-X 400",
    category: "bw",
    colorMatrix: [0.33, 0.59, 0.11, 0.33, 0.59, 0.11, 0.33, 0.59, 0.11],
    toneCurve: {
      r: { blacks: 6, shadows: -4, midtones: 5, highlights: 4, whites: 252 },
      g: { blacks: 6, shadows: -4, midtones: 5, highlights: 4, whites: 252 },
      b: { blacks: 6, shadows: -4, midtones: 5, highlights: 4, whites: 252 },
    },
    saturation: 0,
    temperature: 0,
    tint: 0,
    grain: { amount: 30, size: 2 },
    vignette: 0.2,
    fadeAmount: 6,
    description: "Classic high-contrast B&W with bold grain structure",
  },
  {
    id: "tmax-400",
    name: "T-Max 400",
    category: "bw",
    colorMatrix: [0.3, 0.6, 0.1, 0.3, 0.6, 0.1, 0.3, 0.6, 0.1],
    toneCurve: {
      r: { blacks: 4, shadows: -2, midtones: 3, highlights: 2, whites: 253 },
      g: { blacks: 4, shadows: -2, midtones: 3, highlights: 2, whites: 253 },
      b: { blacks: 4, shadows: -2, midtones: 3, highlights: 2, whites: 253 },
    },
    saturation: 0,
    temperature: 0,
    tint: 0,
    grain: { amount: 18, size: 2 },
    vignette: 0.15,
    fadeAmount: 4,
    description: "Modern tabular-grain B&W, smoother than Tri-X",
  },
  {
    id: "hp5-plus",
    name: "HP5 Plus",
    category: "bw",
    colorMatrix: [0.29, 0.6, 0.11, 0.29, 0.6, 0.11, 0.29, 0.6, 0.11],
    toneCurve: {
      r: { blacks: 8, shadows: -2, midtones: 3, highlights: 2, whites: 250 },
      g: { blacks: 8, shadows: -2, midtones: 3, highlights: 2, whites: 250 },
      b: { blacks: 8, shadows: -2, midtones: 3, highlights: 2, whites: 250 },
    },
    saturation: 0,
    temperature: 0,
    tint: 0,
    grain: { amount: 26, size: 2 },
    vignette: 0.2,
    fadeAmount: 8,
    description: "Versatile B&W with wide tonal range and pleasant grain",
  },
  {
    id: "delta-3200",
    name: "Delta 3200",
    category: "bw",
    colorMatrix: [0.31, 0.58, 0.11, 0.31, 0.58, 0.11, 0.31, 0.58, 0.11],
    toneCurve: {
      r: { blacks: 12, shadows: 0, midtones: 6, highlights: 5, whites: 248 },
      g: { blacks: 12, shadows: 0, midtones: 6, highlights: 5, whites: 248 },
      b: { blacks: 12, shadows: 0, midtones: 6, highlights: 5, whites: 248 },
    },
    saturation: 0,
    temperature: 0,
    tint: 0,
    grain: { amount: 45, size: 3 },
    vignette: 0.25,
    fadeAmount: 12,
    description: "Ultra high-speed B&W with dramatic grain and gritty feel",
  },
  {
    id: "acros-100",
    name: "Acros 100",
    category: "bw",
    colorMatrix: [0.28, 0.62, 0.1, 0.28, 0.62, 0.1, 0.28, 0.62, 0.1],
    toneCurve: {
      r: { blacks: 3, shadows: -1, midtones: 2, highlights: 1, whites: 254 },
      g: { blacks: 3, shadows: -1, midtones: 2, highlights: 1, whites: 254 },
      b: { blacks: 3, shadows: -1, midtones: 2, highlights: 1, whites: 254 },
    },
    saturation: 0,
    temperature: 0,
    tint: 0,
    grain: { amount: 8, size: 1 },
    vignette: 0.1,
    fadeAmount: 3,
    description: "Super fine grain B&W with exceptional tonal graduation",
  },
  {
    id: "cinestill-800t",
    name: "CineStill 800T",
    category: "cinema",
    colorMatrix: [1.05, 0.08, -0.04, -0.02, 0.98, 0.06, -0.06, 0.04, 1.15],
    toneCurve: {
      r: { blacks: 14, shadows: 8, midtones: 5, highlights: 2, whites: 248 },
      g: { blacks: 10, shadows: 4, midtones: -2, highlights: -4, whites: 244 },
      b: { blacks: 16, shadows: 10, midtones: 8, highlights: 5, whites: 250 },
    },
    saturation: 0.95,
    temperature: -12,
    tint: -4,
    grain: { amount: 28, size: 3 },
    vignette: 0.25,
    fadeAmount: 14,
    description: "Cinema film stock with blue tungsten cast and halation glow",
  },
  {
    id: "cinestill-50d",
    name: "CineStill 50D",
    category: "cinema",
    colorMatrix: [1.08, -0.02, 0.02, -0.01, 1.04, 0.01, 0.01, -0.02, 1.04],
    toneCurve: {
      r: { blacks: 6, shadows: 2, midtones: 3, highlights: 1, whites: 252 },
      g: { blacks: 5, shadows: 1, midtones: 2, highlights: 0, whites: 250 },
      b: { blacks: 8, shadows: 4, midtones: 4, highlights: 2, whites: 250 },
    },
    saturation: 1.08,
    temperature: 2,
    tint: -1,
    grain: { amount: 10, size: 1 },
    vignette: 0.12,
    fadeAmount: 6,
    description: "Daylight cinema stock with clean, slightly warm rendering",
  },
]

export function getPresetsByCategory(category: FilmPreset["category"]): FilmPreset[] {
  return FILM_PRESETS.filter(p => p.category === category)
}

export function getPresetById(id: string): FilmPreset | undefined {
  return FILM_PRESETS.find(p => p.id === id)
}
