apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworld
spec:
  selector:
    matchLabels:
      app: spring-helloworld
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
      - name: spring-helloworld
        image: choisunguk/spring-helloworld-prometheus:v1.0
        resources:
          limits:
            memory: "2Gi"
            cpu: "4"
          requests:
            memory: "2Gi"
            cpu: "4"
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >
            -XX:InitialRAMPercentage=65.0 -XX:MaxRAMPercentage=65.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-helloworld
  labels:
    app: spring-helloworld
spec:
  type: NodePort
  selector:
    app: spring-helloworld
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot943
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: spring-helloworld
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
