apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "product-api-no-warmup"
        static_configs:
          - targets: ["product-api-no-warmup:8000"]
            labels:
              variant: "no-warmup"

      - job_name: "product-api-with-warmup"
        static_configs:
          - targets: ["product-api-with-warmup:8000"]
            labels:
              variant: "with-warmup"
