kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocd
nodes:
- role: control-plane
  image: kindest/node:v1.30.4
  extraPortMappings:
  # server nodePortHttp
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  # server nodePortHttps
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
