apiVersion: batch/v1
kind: Job
metadata:
  name: create-testdb
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: create-testdb
        image: mysql:8.0
        command:
        - /bin/sh
        - -c
        - |
          mysql -h $(MYSQL_HOST) -u $(MYSQL_USER) -p$(MYSQL_ROOT_PASSWORD) -e "CREATE DATABASE IF NOT EXISTS $(MYSQL_DATABASE);"
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
      restartPolicy: Never
