apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  # echo -n 'Password1234!!#' | base64
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQxMjM0ISEj
  # echo -n 'admin' | base64
  MYSQL_USER: YWRtaW4=
  # echo -n 'Password1234!!#' | base64
  MYSQL_PASSWORD: UGFzc3dvcmQxMjM0ISEj
  # echo -n 'testdb' | base64
  MYSQL_DATABASE: dGVzdGRi
  # terraform output rds_cluster_endpoint
  # echo -n "{rds_cluster_endpoint}" | base64
  MYSQL_HOST: Y2xvdWR3YXRjaC1hbGFybS1kZW1vLmNsdXN0ZXItY2dkZmI1OW56NGV1LmFwLW5vcnRoZWFzdC0yLnJkcy5hbWF6b25hd3MuY29t
