apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- resources:
  - secrets
  providers:
  - secretbox:
      keys:
      - name: key1
        secret: OVN/X/TIT2uqBd/p9l5PXYSVQm47/mfSDfUQtXn/A4s=
  - identity: {}
