apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.workload.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.workload.name }}"
    app.kubernetes.io/part-of: pull-request-generator-demo
    app.kubernetes.io/component: baseline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.workload.name }}"
      app.kubernetes.io/component: baseline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Values.workload.name }}"
        app.kubernetes.io/part-of: pull-request-generator-demo
        app.kubernetes.io/component: baseline
    spec:
      containers:
        - name: "{{ .Values.workload.name }}"
          image: "{{ .Values.workload.image }}"
          imagePullPolicy: "{{ .Values.workload.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.workload.port }}
          {{- with .Values.workload.env }}
          env:
{{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
{{- toYaml .Values.workload.resources | nindent 12 }}
