apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "{{ .Values.waypoint.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.waypoint.name }}"
    app.kubernetes.io/part-of: pull-request-generator-demo
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
