# PVC Viewer Controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvcviewer-controller-manager
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
