kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mysql
nodes:
- role: control-plane
  image: kindest/node:v1.31.4
  extraPortMappings:
  # mysql
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
- role: worker
  image: kindest/node:v1.31.4
