apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-pubsub-app-config
  namespace: kafka
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC: study-events
  KAFKA_CONSUMER_GROUP: kafka-pubsub-kind
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-pubsub-app
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka-pubsub-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-pubsub-app
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pubsub-app
  template:
    metadata:
      labels:
        app: kafka-pubsub-app
    spec:
      containers:
        - name: app
          image: kafka-pubsub-app:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: kafka-pubsub-app-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
