'use strict';

(function registerSlidesLib(root, factory) {
  const api = typeof module !== 'undefined' && module.exports
    ? factory(
      require('./editor/constants.js'),
      require('./editor/shapes.js'),
      require('./editor/geometry.js'),
      require('./editor/deck.js'),
      require('./editor/presets.js'),
      require('./editor/svg.js'),
      require('./editor/utils.js')
    )
    : factory(
      root.makepresentationEditorConstants,
      root.makepresentationEditorShapes,
      root.makepresentationEditorGeometry,
      root.makepresentationEditorDeck,
      root.makepresentationEditorPresets,
      root.makepresentationEditorSvg,
      root.makepresentationEditorUtils
    );
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.slidesLib = api;
})(globalThis, function createSlidesLib(C, Shapes, Geometry, Deck, Presets, Svg, Utils) {
  return {
    SLIDE_W: C.SLIDE_W,
    SLIDE_H: C.SLIDE_H,
    SLIDE_SIZE_PRESETS: C.SLIDE_SIZE_PRESETS,
    DEFAULT_STYLE: C.DEFAULT_STYLE,
    DEFAULT_IMAGE_STYLE: C.DEFAULT_IMAGE_STYLE,
    DEFAULT_BACKGROUND: C.DEFAULT_BACKGROUND,
    ARROW_ENDS: C.ARROW_ENDS,
    DEFAULT_PRESET_IDS: C.DEFAULT_PRESET_IDS,
    CODE_FORMATS: C.CODE_FORMATS,
    CODE_LANGUAGES: C.CODE_LANGUAGES,
    TEXTUAL: C.TEXTUAL,
    textBox: Svg.textBox,
    ZOOM_STEPS: Utils.ZOOM_STEPS,
    ZOOM_FIT: Utils.ZOOM_FIT,
    zoomIn: Utils.zoomIn,
    zoomOut: Utils.zoomOut,
    filterFonts: Utils.filterFonts,
    createDeck: Deck.createDeck,
    createSlide: Deck.createSlide,
    slideSize: Deck.slideSize,
    setSlideSize: Deck.setSlideSize,
    slideSizePreset: Deck.slideSizePreset,
    pixelsToCentimeters: Deck.pixelsToCentimeters,
    centimetersToPixels: Deck.centimetersToPixels,
    slideBackground: Deck.slideBackground,
    normalizeLineNumbers: Shapes.normalizeLineNumbers,
    tokenizeCodeLine: Svg.tokenizeCodeLine,
    createShape: Shapes.createShape,
    defaultPresetShapes: Presets.defaultPresetShapes,
    customPresetFromSelection: Presets.customPresetFromSelection,
    parseClipboardShapes: Shapes.parseClipboardShapes,
    dragShape: Geometry.dragShape,
    isDegenerate: Geometry.isDegenerate,
    shapeBBox: Geometry.shapeBBox,
    shapeSelectionContainsPoint: Geometry.shapeSelectionContainsPoint,
    normalizeRect: Geometry.normalizeRect,
    shapeIndicesInRect: Geometry.shapeIndicesInRect,
    toggleSelection: Geometry.toggleSelection,
    moveShape: Geometry.moveShape,
    visualShapeBBox: Geometry.visualShapeBBox,
    boundsForShapes: Geometry.boundsForShapes,
    alignShapes: Geometry.alignShapes,
    snapMove: Geometry.snapMove,
    groupShapes: Geometry.groupShapes,
    ungroupShapes: Geometry.ungroupShapes,
    groupIndicesFor: Geometry.groupIndicesFor,
    cloneShapes: Shapes.cloneShapes,
    setCrop: Shapes.setCrop,
    handlesFor: Geometry.handlesFor,
    resizeShape: Geometry.resizeShape,
    resizeShapeConstrained: Geometry.resizeShapeConstrained,
    rotationHandleFor: Geometry.rotationHandleFor,
    rotationTowards: Geometry.rotationTowards,
    unrotateDelta: Geometry.unrotateDelta,
    addSlide: Deck.addSlide,
    deleteSlide: Deck.deleteSlide,
    moveSlide: Deck.moveSlide,
    moveSlideAtEdge: Deck.moveSlideAtEdge,
    moveSlideSelection: Deck.moveSlideSelection,
    duplicateSlide: Deck.duplicateSlide,
    slideNumberShape: Deck.slideNumberShape,
    escapeXml: Svg.escapeXml,
    wrapTextLines: Svg.wrapTextLines,
    fitTextBox: Svg.fitTextBox,
    rotateSvg: Svg.rotateSvg,
    renderShapeSvg: Svg.renderShapeSvg,
    renderSlideSvg: Svg.renderSlideSvg,
    renderShapesSvg: Svg.renderShapesSvg,
  };
});
