apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-mutation
  namespace: default
webhooks:
- name: pod-mutation.default.com
  sideEffects: None
  failurePolicy: Fail
  admissionReviewVersions:
  - v1
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  clientConfig:
    service:
      name: admission-server
      namespace: default
      path: /mutate/
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUvRENDQXVTZ0F3SUJBZ0lVWHVMUXdCOUFkaWNrWFlLcEdzYkxteXBVTzFJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF3d0hiV0ZzZDJGeVpUQWVGdzB5TkRBNE1UWXhNekkwTURSYUZ3MHlOVEE0TVRZeApNekkwTURSYU1CSXhFREFPQmdOVkJBTU1CMjFoYkhkaGNtVXdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDCkR3QXdnZ0lLQW9JQ0FRRFlJcjFVd1Ezd3J4UkFxdlZvSllrZ1RtT1E2NHRVcTExeSt1Ui9ySXY3M0hRVVBGcUMKdHNvVUFCNis0T2hXUzA0QUd0ZmlSNUlnUjNCZEs0ODk3K1BCNGl6ZjNJM3lOQlhMR1dSd2dCV093cE0zTTNKbwpNR1NVS0tZUW5SamZLZnY5NHJ1ZmJhQUx3clFFZHcwMVJSeGF5Y2E2TTNob2lCR29idUJsRXprZDAzS001b2lMCnIrK08yUnNNZmROWDVkMFl4M3FwTEhoenpPZGtDYnZ0TFN5NXY5Y0F2RmNhcE5IOHdYU25ueldLQlpRRWV2VmMKdmZZWnBOK3lrRVpNa3BBNDBmSENRY0F2dVpvWFdPMnRqRkVuRTVRUUJWWC9mRTFkRzI1MHlUbkE4Zmp5cTFuUApnbHpwWnZuNDk5KzBocUJsKzc3ZHl3ZmF6V3J2UWZ3UFRHa0JoODFabWFNWTI0ZWF5ZHhianVNV2ZvdC9ad1ZKCkF4ck9wWlNQUXpSVUkzaVdsemwraHd3elNsWHVBdWh2dzEyRlNra2l1WGNzdm1HT2VKVzAvVzg1TzI4bHUvcngKRlhMQWRWOWN2NWtPYkg0cEJlUTNOUzBjVXU1QktiOE1tUHdFSGtodXhHa3RzVzkvUHRQMkdHaFRkRjMyRk8vZApjMWdzU1ByUlQ0SWZ0U1ZEWlc1OElzQXBZNHpiTzVQNjVqVGRDbnZWVlVnbXc1eU9rbi9Jc2poWFI4QndxQ29nCnFyL1VSL0gwekVSWnJUKzJzVTFxSVJ2VWRTWDh1dW04eGliL3NUWmdoSnZlaVZ1UHNPMWQwcDE2R0lHVFc3K3gKaUJYZDFyUmlFcm5YcFNNeUVtSlRIRk8yNm1EOG5PT1FFamxhUUlzMjFwc3pZbnNqR1RwVDdGU21td0lEQVFBQgpvMG93U0RBbkJnTlZIUkVFSURBZWdoeGhaRzFwYzNOcGIyNHRjMlZ5ZG1WeUxtUmxabUYxYkhRdWMzWmpNQjBHCkExVWREZ1FXQkJROFQ2c0EzdUtFUHRrNkZPTWpjRmpFblVjcEp6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUEKYzRQWHZPeStwT1hpenVveUZuQUNHN3dnNEs4cjJJWi9JSWtqcWlPb0FkT2F5aG5iRkJLdm04UzZocVRnVXloRApOYXJESXQvTmNtc28ydy9Ldm41cEpBS2VPZXBzd3hDd2l0UmxCNGVGeWFXZEEzOGtZWWNpcVM3ZG8yMEUyQkx4Cmw1QmRxMnpFdHJjd0JKYXFtMm16cU8vRk5wVEtaVThwcUNtdlpyN25aVXA5dVhnWjZMV2w4MytmMjdERTRpRWwKRnYyaStlUlh2MVp1ZURYWlJ5QTlINElBVjJGWk5tV0docjRiMDZEMEhRclVqUldmdi9KOW5qbDNkSEtVd0ZTUgpzSEd4N3Y2R0JkRGxEUFR6ZGUwQzZRZHNvTDcvV3EvVC9VTWpnajdHTVhZcnlTUVMvbXhGdU9UaFBYRUQxRWRnCnlHVWJZaTQrQk5USEROTm15OUhXa2tkelFTa0I2d08xeCthMjdyd0c0QnpRRE8xNDVIekJVMXJpT2RqK1l6OW8KaFR4RWF6dk9UNld6b3laZEhidUVOZ0hnTWNsNHQ4UExhaUp5cjgzRmtYU1p1U0NaZExybE1qMzl0WlJjTjBTdgpkYjhsMW43TzR3NTcxUWxzZ0ZjKzQ2OEN3cFJna0hxYXVWelpmdGREZ201a2YvWGFhU1pjelJiazBZSHpxa0RuClMyUFZBbUZYRHpDcUw2QWNUM2d5ejdlald3RUVDMEt5KzMydHgxMHRzaTlaWXVFZXRwZWhHS1JVeWNqQkk0TEQKYW5zS1o3cmdncTVSVlBkWFlWQTgrVWx2a09MNUJoNlE0ZUZHUG8zY2dmNGVvNURHVS8yVVZmSkhPNlZZUFZONgordXZVMlpxSjBpeFVOd2VMRlJBUFdjN3pBbXZkek82L1B2UmptREJuRHBJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
