kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubeflow
nodes:
- role: control-plane
  image: kindest/node:v1.33.2
  # nginx-ingress port
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # nginx-ingress port
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.33.2
- role: worker
  image: kindest/node:v1.33.2
