kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cgroup-cpu
nodes:
- role: control-plane
  image: kindest/node:v1.29.1
- role: worker
  image: kindest/node:v1.29.1
  labels:
    tier: infra
- role: worker
  image: kindest/node:v1.29.1
  labels:
    tier: service-a
