apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-env-config
  namespace: nextjs-env-secret
  labels:
    app.kubernetes.io/name: nextjs-env-secret-demo
data:
  RUNTIME_CONFIG_NAME: "local-runtime-v1"
