apiVersion: v1
kind: Secret
metadata:
  name: nextjs-runtime-secret
  namespace: nextjs-env-secret
  labels:
    app.kubernetes.io/name: nextjs-env-secret-demo
type: Opaque
stringData:
  RUNTIME_SECRET_TOKEN: "local-demo-secret-v1"
