apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-server-headless
  labels:
    app.kubernetes.io/name: tcp-echo-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: k8s-haproxy-tcp
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: tcp-echo-server
    app.kubernetes.io/component: server
  ports:
    - name: tcp
      port: 9090
      protocol: TCP
      targetPort: tcp
