# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-22.04"

  # config.vm.provider "vmware_desktop" do |v|
  #   v.memory = 1024
  #   v.cpus = 2
  # end

#   config.vm.provision "shell", inline: <<-SHELL
#     sudo apt-get update
#     sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
#     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#     sudo apt-get update
#     sudo apt-get install -y docker-ce docker-ce-cli containerd.io
#     sudo usermod -aG docker $USER
#   SHELL
# end


NODE_COUNT = 1
VAULT_VERSION = "1.13.0"

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|

    # vault listen port
    config.vm.network "forwarded_port", guest: 8300, host: 8200 + i - 1

    config.vm.provider "vmware_desktop" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    config.vm.define "vault#{i}" do |vault|
      vault.vm.box = "bento/ubuntu-22.04"
      vault.vm.hostname = "vault#{i}"

      vault.vm.provision "shell", inline: <<-SHELL
        DEBIAN_FRONTEND=noninteractive sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common unzip vim gpg wget

        # install vault
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install vault
      SHELL
    end
  end
end
