kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cilium
nodes:
- role: control-plane
  image: kindest/node:v1.30.4
  # kubeadmConfigPatches:
  # - |
  #   kind: InitConfiguration
  #   nodeRegistration:
  #     kubeletExtraArgs:
  #       node-labels: "ingress-ready=true"
- role: worker
  image: kindest/node:v1.30.4
- role: worker
  image: kindest/node:v1.30.4
networking:
  disableDefaultCNI: true
