apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-request-cpu2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-request-cpu2
  template:
    metadata:
      labels:
        app: busybox-request-cpu2
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - service-a
      containers:
      - name: busybox
        image: busybox
        command:
        - sh
        - -c
        - while :; do :; done
        resources:
          requests:
            cpu: "0.5"
