services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sysbench_test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '2'
          memory: 1024M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  sysbench_test:
    driver: bridge

volumes:
  mysql_data:
