apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    # 로컬에서 접근할 수 있도록 NodePort로 설정
    # 주의: 테스트 환경에서만 사용, 프로덕션은 nodePort 사용하는 것을 추천하지 않음
    nodePort: 30080
  selector:
    app: mysql
  type: NodePort
