services:
  postgres:
    image: postgres:16-alpine
    container_name: pg-concurrently-lab
    environment:
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
      POSTGRES_DB: labdb
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ../sql:/sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab -d labdb"]
      interval: 3s
      timeout: 3s
      retries: 10
    command:
      - "postgres"
      - "-c"
      - "log_min_duration_statement=0"
      - "-c"
      - "log_lock_waits=on"
