[project]
name = "minist-with-keras"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keras>=3.11.2",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "tensorflow>=2.20.0",
]
