kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio
nodes:
- role: control-plane
  image: kindest/node:v1.31.4
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # istio ingress controller
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # istio ingress controller
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.31.4
- role: worker
  image: kindest/node:v1.31.4
