apiVersion: v1
kind: Pod
metadata:
  name: mitmproxy
  namespace: shopping
  labels:
    app: mitmproxy
spec:
  containers:
  - name: mitmweb
    image: mitmproxy/mitmproxy
    command: ["mitmweb"]
    args: ["--web-host", "0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
  namespace: shopping
spec:
  type: NodePort
  selector:
    app: mitmproxy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32101
    name: mitmproxy
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 32102
    name: mitmweb
