# ML Pipeline Scheduled Workflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: minio
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
# ML Pipeline Scheduled Workflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
          limits:
            cpu: 120m
            memory: 100Mi
---
# ML Pipeline Scheduled Workflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-ui
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
# ML Pipeline Scheduled Workflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-visualizationserver
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-visualizationserver
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
---
# ML Pipeline Scheduled Workflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 500Mi
---
# ML Pipeline Scheduled Workflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: workflow-controller
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
