IMAGE_NAME = "centos/7"

# number of worker nodes
WORKER_N = 2
MASTER_N = 1

# IP config
MASTER_IP = "192.168.219."
NODE_IP = "192.168.219."
BOOTSTRAP_IP = "192.168.219.210"

# System config
MASTER_CPU = 4
MASTER_MEMORY = 4096
WORKER_CPU = 4
WORKER_MEMORY = 16384

# hostname
MASTER_HOSTNAME = "kube-master"
WORKER_HOSTNAME = "kube-worker"
BOOSTSTRAP_HOSTNAME = "kube-bootstrap"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # bootstrap
  config.vm.define BOOSTSTRAP_HOSTNAME do |cfg|
    cfg.vm.box = IMAGE_NAME
    cfg.vm.network "public_network", ip: BOOTSTRAP_IP
    cfg.vm.hostname = BOOSTSTRAP_HOSTNAME
    
    cfg.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 4
      v.name = BOOSTSTRAP_HOSTNAME
    end
    
    # set environment
    cfg.vm.provision "file", source: "bootstrap.sh", destination: "bootstrap.sh"
    cfg.vm.provision "shell", inline: "bash bootstrap.sh"

    # copy ansible inventory
    cfg.vm.provision "file", source: "inventory.ini", destination: "kubespray/inventory/mycluster/inventory.ini"
  end

  # master node
  (1..MASTER_N).each do |i|
    config.vm.define "#{MASTER_HOSTNAME}-#{i}" do |node|
        node.vm.provider "virtualbox" do |v|
          v.memory = MASTER_MEMORY
          v.cpus = MASTER_CPU
          v.name = "#{MASTER_HOSTNAME}-#{i}"
        end

        node.vm.box = IMAGE_NAME
        node.vm.network "public_network", ip: MASTER_IP + "#{i + 231}"
        node.vm.hostname = "#{MASTER_HOSTNAME}-#{i}"
        
        # set environment
        node.vm.provision "file", source: "node.sh", destination: "node.sh"
        node.vm.provision "shell", inline: "bash node.sh"
      end
  end

  # worker node
  (1..WORKER_N).each do |i|
    config.vm.define "#{WORKER_HOSTNAME}-#{i}" do |node|
        node.vm.provider "virtualbox" do |v|
          v.memory = WORKER_MEMORY
          v.cpus = WORKER_CPU
          v.name = "#{WORKER_HOSTNAME}-#{i}"
        end

        node.vm.box = IMAGE_NAME
        node.vm.network "public_network", ip: NODE_IP + "#{i + 231}"
        node.vm.hostname = "#{WORKER_HOSTNAME}-#{i}"

        # set environment
        node.vm.provision "file", source: "node.sh", destination: "node.sh"
        node.vm.provision "shell", inline: "bash node.sh"
      end
  end
end