version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: django_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: memo_db
      MYSQL_USER: memo
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
