apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
      - name: argo-rollouts-extension
        image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.1
        env:
        - name: EXTENSION_URL
          value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
        volumeMounts:
        - name: extensions
          mountPath: /tmp/extensions/
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
      containers:
      - name: argocd-server
        volumeMounts:
        - name: extensions
          mountPath: /tmp/extensions/
      volumes:
      - name: extensions
        emptyDir: {}
