apiVersion: v1
kind: PersistentVolume
metadata:
  name: chapter5-data-pv
  labels:
    app.kubernetes.io/name: chapter5-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/genai-ch5/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chapter5-data-pvc
  labels:
    app.kubernetes.io/name: chapter5-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: chapter5-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chapter5-notebooks-pv
  labels:
    app.kubernetes.io/name: chapter5-notebooks
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/genai-ch5/notebooks
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chapter5-notebooks-pvc
  labels:
    app.kubernetes.io/name: chapter5-notebooks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeName: chapter5-notebooks-pv
