apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: pr-preview
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/part-of: pr-preview-kind
spec:
  selector:
    app.kubernetes.io/name: zipkin
  ports:
    - name: http
      port: 9411
      targetPort: 9411
