apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: on-demand
spec:
  template:
    metadata:
      labels:
        app: inflate
    spec:
      taints:
      - key: app
        value: inflate
        effect: NoSchedule
      requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: [ "t" ]
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values: [ "nano", "micro", "small" ]
      - key: "karpenter.k8s.aws/instance-generation"
        operator: Gt
        values: [ "2" ]
      - key: "kubernetes.io/arch"
        operator: In
        values: [ "amd64" ]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: [ "on-demand" ]
      - key: capacity-spread
        operator: In
        values:
        - "on-demand-1"
        - "on-demand-2"
        - "on-demand-3"
        - "on-demand-4"
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: on-demand
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
