name: Build SpringBoot with CodeBuild - build in AWS network

on:
  # pull_request:
  #   types: [closed]
  #   paths:
  #     - 'aws/codebuild/github_action/applications/springboot_app/**'
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  build:
    # if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on:
      - codebuild-github-action-github-action-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'EOF'
          <settings>
            <servers>
              <server>
                <id>private-nexus-releases</id>
                <username>${env.MAVEN_USERNAME}</username>
                <password>${env.MAVEN_PASSWORD}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>nexus-internal</id>
                <repositories>
                  <repository>
                    <id>private-nexus-releases</id>
                    <url>https://nexus-internal.choilab.xyz/repository/maven-releases/</url>
                    <releases>
                      <enabled>true</enabled>
                    </releases>
                  </repository>
                  <repository>
                    <id>central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                    <releases>
                      <enabled>true</enabled>
                    </releases>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>nexus-internal</activeProfile>
            </activeProfiles>
          </settings>
          EOF
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build
        working-directory: aws/codebuild/github_action/applications/springboot_app/codebuild
        run: mvn clean package -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
