name: Build SpringBoot with CodeBuild - build in github network

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build
        working-directory: aws/codebuild/github_action/applications/springboot_app/codebuild
        run: mvn package -DskipTests
