apiVersion: v1
kind: Service
metadata:
  name: loyalty-inference-service
  namespace: jupyterhub
  labels:
    app.kubernetes.io/name: loyalty-inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loyalty-inference
  ports:
    - name: http
      port: 80
      targetPort: 80
