services:
  ## firebaes-admin 9.4.3
  springboot943:
    image: choisunguk/fcm-push:9.4.3-rc.1
    volumes:
      - ./docker-config/springboot/firebase-adminsdk.json:/app/firebase-adminsdk.json
    ports:
      - "8080:8080"

  ## firebase-admin 9.2.0
  springboot920:
    image: choisunguk/fcm-push:9.2.0-rc.1
    volumes:
      - ./docker-config/springboot/firebase-adminsdk.json:/app/firebase-adminsdk.json
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker-config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password1234
    volumes:
      - ./docker-config/grafana/provisioning:/etc/grafana/provisioning
